apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v0.29
          resources:
            requests:
              cpu: 50m
              memory: 80Mi
            limits:
              cpu: 250m
              memory: 250Mi
          ports:
            - containerPort: 7700
          envFrom:
            - configMapRef:
                name: meilisearch-config-env
            - secretRef:
                name: meilisearch-secret-env
          volumeMounts:
            - name: meilisearch-data
              mountPath: /meili_data
      volumes:
        - name: meilisearch-data
          persistentVolumeClaim:
            claimName: meilisearch-pvc
